### ISSUE TITLE
As a player that has entered the game, I want to be able to write on the screen while viewing them in order to imitate them.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-template-client#12]
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#11

- [x] sopra-fs23-group-16/sopra-fs23-template-server#58

- [x] sopra-fs23-group-16/sopra-fs23-template-server#59

- [x] sopra-fs23-group-16/sopra-fs23-template-server#60

- [x] sopra-fs23-group-16/sopra-fs23-template-server#61

- [ ] sopra-fs23-group-16/sopra-fs23-template-server#62
